//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTXMania2.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTXMania.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All On/Off.
        /// </summary>
        internal static string AllONOFF {
            get {
                return ResourceManager.GetString("AllONOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is allready running.
        /// </summary>
        internal static string AllreadyRunning {
            get {
                return ResourceManager.GetString("AllreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned input list.
        /// </summary>
        internal static string AssignedInputList {
            get {
                return ResourceManager.GetString("AssignedInputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic play.
        /// </summary>
        internal static string AutoPlay {
            get {
                return ResourceManager.GetString("AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display pos of China.
        /// </summary>
        internal static string ChinaDispPos {
            get {
                return ResourceManager.GetString("ChinaDispPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice....
        /// </summary>
        internal static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current allocation.
        /// </summary>
        internal static string CurrentAllocation {
            get {
                return ResourceManager.GetString("CurrentAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cymbal Free.
        /// </summary>
        internal static string CymbalFree {
            get {
                return ResourceManager.GetString("CymbalFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes?.
        /// </summary>
        internal static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Sound.
        /// </summary>
        internal static string DrumSound {
            get {
                return ResourceManager.GetString("DrumSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter keyboard or midi signal.
        /// </summary>
        internal static string EnterKeyboardOrMidi {
            get {
                return ResourceManager.GetString("EnterKeyboardOrMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot pedal opening.
        /// </summary>
        internal static string FootPedalOpening {
            get {
                return ResourceManager.GetString("FootPedalOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please hit the pad.
        /// </summary>
        internal static string HitPad {
            get {
                return ResourceManager.GetString("HitPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore active signal.
        /// </summary>
        internal static string IgnoreActive {
            get {
                return ResourceManager.GetString("IgnoreActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        internal static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Settings.
        /// </summary>
        internal static string InitSettings {
            get {
                return ResourceManager.GetString("InitSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Song DB.
        /// </summary>
        internal static string InitSongDb {
            get {
                return ResourceManager.GetString("InitSongDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input allocation.
        /// </summary>
        internal static string InputAlloc {
            get {
                return ResourceManager.GetString("InputAlloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input assigned to pad.
        /// </summary>
        internal static string InputAssigned {
            get {
                return ResourceManager.GetString("InputAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input list.
        /// </summary>
        internal static string InputList {
            get {
                return ResourceManager.GetString("InputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep of input thread.
        /// </summary>
        internal static string InputSleep {
            get {
                return ResourceManager.GetString("InputSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value.
        /// </summary>
        internal static string InputValue {
            get {
                return ResourceManager.GetString("InputValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you hit the keyboard or MIDI drum, the input value is displayed below. \ nIf you select the input value and press the &quot;Add&quot; button, the input value is assigned to the pad. \ n &quot;.
        /// </summary>
        internal static string KeyboardInfo {
            get {
                return ResourceManager.GetString("KeyboardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane arrangement.
        /// </summary>
        internal static string LaneArr {
            get {
                return ResourceManager.GetString("LaneArr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane transparency.
        /// </summary>
        internal static string LaneTrans {
            get {
                return ResourceManager.GetString("LaneTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value.
        /// </summary>
        internal static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure the maximum value and minimum value by stepping on or releasing the foot pedal.
        ///Measure
        ///Käännökset tekstille measure
        ///SubstantiiviYleisyys
        ///計測
        ///measurement, measure
        ///手段
        ///means, way, measure
        ///施策
        ///measure, policy
        ///措置
        ///measure, step
        ///尺
        ///scale, length, measure, rule
        ///物指
        ///ruler, measure
        ///升
        ///measure
        ///加減
        ///adjustment, degree, addition and subtraction, allowance, moderation, extent
        ///一節
        ///passage, verse, paragraph, stanza, strain, measure
        ///丈
        ///length, stature, measure
        ///約数
        ///measure
        ///Verbi
        ///測る
        ///measure, weigh,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MeasureMaxMin {
            get {
                return ResourceManager.GetString("MeasureMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Speed.
        /// </summary>
        internal static string MusicSpeed {
            get {
                return ResourceManager.GetString("MusicSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple launch is not possible.
        /// </summary>
        internal static string NoMultipleRuns {
            get {
                return ResourceManager.GetString("NoMultipleRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I could not confirm it.
        /// </summary>
        internal static string NotConfirm {
            get {
                return ResourceManager.GetString("NotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pad.
        /// </summary>
        internal static string Pad {
            get {
                return ResourceManager.GetString("Pad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select the pad to set. \ nIf you select the assigned input value and press the &quot;Delete&quot; button, that input value will be deleted from the pad. \ n.
        /// </summary>
        internal static string PadInfo {
            get {
                return ResourceManager.GetString("PadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance mode.
        /// </summary>
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present value.
        /// </summary>
        internal static string PresentValue {
            get {
                return ResourceManager.GetString("PresentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display pos of Ride.
        /// </summary>
        internal static string RideDispPos {
            get {
                return ResourceManager.GetString("RideDispPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen mode.
        /// </summary>
        internal static string ScreenMode {
            get {
                return ResourceManager.GetString("ScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a player.
        /// </summary>
        internal static string SelectPlayer {
            get {
                return ResourceManager.GetString("SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings done (return).
        /// </summary>
        internal static string SettingsDone {
            get {
                return ResourceManager.GetString("SettingsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song folder.
        /// </summary>
        internal static string SongFolder {
            get {
                return ResourceManager.GetString("SongFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song reading folder.
        /// </summary>
        internal static string SongReadingFolder {
            get {
                return ResourceManager.GetString("SongReadingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song reading folder list.
        /// </summary>
        internal static string SongReadingFolderList {
            get {
                return ResourceManager.GetString("SongReadingFolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display pos of Splash.
        /// </summary>
        internal static string SplashDispPos {
            get {
                return ResourceManager.GetString("SplashDispPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We started accepting.
        /// </summary>
        internal static string StartedAccepting {
            get {
                return ResourceManager.GetString("StartedAccepting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing clock signal.
        /// </summary>
        internal static string TimingClock {
            get {
                return ResourceManager.GetString("TimingClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsipported device.
        /// </summary>
        internal static string UnsupportedDevice {
            get {
                return ResourceManager.GetString("UnsupportedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
