//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSTFEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSTFEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Config.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIG_FILE_NAME {
            get {
                return ResourceManager.GetString("CONFIG_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CopyHS {
            get {
                object obj = ResourceManager.GetObject("CopyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CutHS {
            get {
                object obj = ResourceManager.GetObject("CutHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_NewRecordHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_NewRecordHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DocumentHS {
            get {
                object obj = ResourceManager.GetObject("DocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap DownArrowHS {
            get {
                object obj = ResourceManager.GetObject("DownArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Edit_RedoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_RedoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Edit_UndoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   6912 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GRID_PER_PART {
            get {
                return ResourceManager.GetString("GRID_PER_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   27 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GRID_PER_PIXEL {
            get {
                return ResourceManager.GetString("GRID_PER_PIXEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set BPM value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_BPM選択ダイアログの説明文 {
            get {
                return ResourceManager.GetString("MSG_BPM選択ダイアログの説明文", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to load it and convert to SSTFormat? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_SSTF形式に変換します {
            get {
                return ResourceManager.GetString("MSG_SSTF形式に変換します", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_エラーダイアログのタイトル {
            get {
                return ResourceManager.GetString("MSG_エラーダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait a minute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_しばらくお待ち下さい {
            get {
                return ResourceManager.GetString("MSG_しばらくお待ち下さい", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exe files (*.exe)|*.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ビュアー選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("MSG_ビュアー選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Song file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ファイル選択ダイアログのタイトル {
            get {
                return ResourceManager.GetString("MSG_ファイル選択ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving now... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_保存中です {
            get {
                return ResourceManager.GetString("MSG_保存中です", resourceCulture);
            }
        }
        
        /// <summary>
        ///    chips were selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_個のチップが選択されました {
            get {
                return ResourceManager.GetString("MSG_個のチップが選択されました", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_対応していないファイルです {
            get {
                return ResourceManager.GetString("MSG_対応していないファイルです", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Part memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_小節メモ {
            get {
                return ResourceManager.GetString("MSG_小節メモ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid number in start part. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_小節番号に誤りがあります {
            get {
                return ResourceManager.GetString("MSG_小節番号に誤りがあります", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song files (*.sstf;*.dtx;*.gda;*.g2d;*.bms;*.bme)|*.sstf;*.dtx;*.gda;*.g2d;*.bms;*.bme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_曲ファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("MSG_曲ファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_検索結果ダイアログのタイトル {
            get {
                return ResourceManager.GetString("MSG_検索結果ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image files (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_画像ファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("MSG_画像ファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_確認ダイアログのタイトル {
            get {
                return ResourceManager.GetString("MSG_確認ダイアログのタイトル", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save changes to file ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_編集中のデータを保存しますか {
            get {
                return ResourceManager.GetString("MSG_編集中のデータを保存しますか", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media files (*.mp4;*.avi;*.wmv;*.mpg;*.mpeg;*.wav;*.ogg;*.xa;*.mp3)|*.mp4;*.avi;*.wmv;*.mpg;*.mprg;*.wav;*.ogg;*.xa;*.mp3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_背景動画ファイル選択ダイアログのフィルタ {
            get {
                return ResourceManager.GetString("MSG_背景動画ファイル選択ダイアログのフィルタ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chips not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_該当するチップはありませんでした {
            get {
                return ResourceManager.GetString("MSG_該当するチップはありませんでした", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading now... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_読み込み中です {
            get {
                return ResourceManager.GetString("MSG_読み込み中です", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NEW_FILENAME {
            get {
                return ResourceManager.GetString("NEW_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PasteHS {
            get {
                object obj = ResourceManager.GetObject("PasteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DTXMania.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PLAYER_NAME {
            get {
                return ResourceManager.GetString("PLAYER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PlayFromStart {
            get {
                object obj = ResourceManager.GetObject("PlayFromStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PointerHS {
            get {
                object obj = ResourceManager.GetObject("PointerHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap StopHS {
            get {
                object obj = ResourceManager.GetObject("StopHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap UpArrowHS {
            get {
                object obj = ResourceManager.GetObject("UpArrowHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap りらちょー {
            get {
                object obj = ResourceManager.GetObject("りらちょー", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap 既定のプレビュー画像 {
            get {
                object obj = ResourceManager.GetObject("既定のプレビュー画像", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
